language: go
addons:
  postgresql: "9.4"
go:
 - tip
before_install:
 - go get github.com/tools/godep
 - go get github.com/mattn/goveralls
 - go get golang.org/x/tools/cmd/cover
 - go get golang.org/x/lint/golint
 - go get golang.org/x/tools/cmd/goimports
install: godep restore
script:
 - ./scripts/cover.sh
 - ./scripts/dredd.sh
after_success:
 - ./scripts/dockerhub.sh
